##This file contains strings that have to be detected by django-admin.py
##makemessages

## country names
_("Austria")
_("Florence")
_("France")
_("Milan")
_("Naples")
_("Papacy")
_("Turks")
_("Venice")
_("Savoy")
_("H. Roman Empire")
_("Genoa")
_("Spanish Empire")

## scenario names
_("Development")
_("The Spanish Preponderance")
_("The Balance of Power")
_("Struggle for Dominance I")
_("Struggle for Dominance II")
_("The Death of the Duke of Milan")

## area names (excluding the areas whose name is the one of a country)
_("Albania")
_("Ancona")
_("Aquila")
_("Arezzo")
_("Avignon")
_("Bari")
_("Bergamo")
_("Bologna")
_("Bosnia")
_("Capua")
_("Carniola")
_("Carinthia")
_("Central Mediterranean")
_("Como")
_("Corsica")
_("Cremona")
_("Croatia")
_("Dalmatia")
_("Durazzo")
_("Ferrara")
_("Fornovo")
_("Friuli")
_("Genoa")
_("Gulf of Lions")
_("Gulf of Naples")
_("Herzegovina")
_("Hungary")
_("Ionian Sea")
_("Istria")
_("Lower Adriatic")
_("Ligurian Sea")
_("Lucca")
_("Mantua")
_("Marseille")
_("Messina")
_("Modena")
_("Montferrat")
_("Otranto")
_("Padua")
_("Palermo")
_("Parma")
_("Patrimony")
_("Pavia")
_("Perugia")
_("Piombino")
_("Pistoia")
_("Pisa")
_("Provence")
_("Ragusa")
_("Rome")
_("Salerno")
_("Saluzzo")
_("Sardinia")
_("Savoy")
_("Siena")
_("Slavonia")
_("Spoleto")
_("Swiss")
_("Treviso")
_("Trent")
_("Thyrrenian Sea")
_("Tunis")
_("Turin")
_("Tyrol")
_("Upper Adriatic")
_("Urbino")
_("Venice")
_("Verona")
_("Western Mediterranean")

## Special units titles
_("Regular")
_("Citizen militia")
_("Elite mercenaries")
_("Elite professionals")

## subject of the signup code email
_("Create an acccount on %(domain)s")
