from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.views.decorators.cache import cache_page

import machiavelli.views as views

urlpatterns = patterns('machiavelli.views',
	url(r'^$', views.SummaryView.as_view(), name='summary'),
	url(r'^games/all_finished$',
		views.AllFinishedGamesList.as_view(),
		name="games-all-finished"), 
	url(r'^games/finished$',
		views.MyFinishedGamesList.as_view(),
		name="games-my-finished"), 
	url(r'^games/other_active$',
		views.OtherActiveGamesList.as_view(),
		name="games-other-active"), 
	url(r'^games/my_active$',
		views.MyActiveGamesList.as_view(),
		name="games-my-active"), 
	url(r'^games/joinable$',
		views.JoinableGamesList.as_view(),
		name="games-joinable"), 
	url(r'^games/pending$',
		views.PendingGamesList.as_view(),
		name='games-pending'),
	url(r'^revolutions$',
		views.RevolutionList.as_view(),
		name='revolution_list'),
	url(r'^ranking$',
		views.HallOfFameView.as_view(),
		name='hall-of-fame'),
	url(r'^ranking/(?P<key>[-\w]+)/(?P<val>[-\w]+)$', 'ranking', name='ranking'),
	url(r'^overthrow/(?P<revolution_id>\d+)', 'overthrow', name='overthrow'),
	url(r'^undo_overthrow/(?P<revolution_id>\d+)', 'undo_overthrow', name='undo_overthrow'),
	url(r'^new_game$', 'create_game', name='new-game'),
	url(r'^new_team_game$', 'create_game', kwargs={'teams': True}, name='new_team_game'),
	url(r'^game/(?P<slug>[-\w]+)/invite$', 'invite_users', name='invite-users'),
	url(r'^game/(?P<slug>[-\w]+)/join$', 'join_game', name='join-game'),
	url(r'^game/(?P<slug>[-\w]+)/public$', 'make_public', name='make-public'),
	url(r'^game/(?P<slug>[-\w]+)/leave$', 'leave_game', name='leave-game'),
	url(r'^game/(?P<slug>[-\w]+)/log$', 'logs_by_game', name='game-log'),
	url(r'^game/(?P<slug>[-\w]+)/areas$',
		views.GameAreaListView.as_view(),
		name='gamearea-list'),
	url(r'^game/(?P<slug>[-\w]+)/turn$',
		views.TurnLogListView.as_view(),
		name='turn-log-list'),
	url(r'^game/(?P<slug>[-\w]+)/excommunicate/(?P<player_id>\d+)',
		views.ExcommunicationView.as_view(action="punish"),
		name='excommunicate'),
	url(r'^game/(?P<slug>[-\w]+)/forgive/(?P<player_id>\d+)',
		views.ExcommunicationView.as_view(action="forgive"),
		name='forgive-excommunication'),
	url(r'^game/(?P<slug>[-\w]+)/lend/(?P<player_id>\d+)',
		views.GiveMoneyView.as_view(),
		name='lend'),
	url(r'^game/(?P<slug>[-\w]+)/borrow$',
		views.BorrowMoneyView.as_view(),
		name='borrow-money'),
	url(r'^game/(?P<slug>[-\w]+)/repay/(?P<credit_id>\d+)$',
		views.ReturnMoneyView.as_view(),
		name='return-credit'),
	url(r'^game/(?P<slug>[-\w]+)/assassination$',
		views.AssassinationView.as_view(),
		name='assassination'),
	url(r'^game/(?P<slug>[-\w]+)/confirm_orders$',
		views.ConfirmOrdersView.as_view(),
		name='confirm-orders'),
	url(r'^game/(?P<slug>[-\w]+)/undo$',
		views.UndoActionsView.as_view(),
		name='undo-actions'),
	url(r'^game/(?P<slug>[-\w]+)/surrender$',
		views.SurrenderView.as_view(),
		name='surrender'),
	url(r'^game/(?P<slug>[-\w]+)/delete_order/(?P<order_id>\d+)$',
		views.DeleteOrderView.as_view(),
		name='delete-order'),
	url(r'^game/(?P<slug>[-\w]+)/expenses$',
		views.ExpenseCreateView.as_view(),
		name='expenses'),
	url(r'^game/(?P<slug>[-\w]+)/undo_expense/(?P<expense_id>\d+)$',
		views.ExpenseDeleteView.as_view(),
		name='undo-expense'),
	url(r'^game/(?P<slug>[-\w]+)/taxation$', 'taxation', name='taxation'),
	url(r'^game/(?P<slug>[-\w]+)/whisper$',
		views.WhisperCreateView.as_view(),
		name='new-whisper'),
	url(r'^game/(?P<slug>[-\w]+)/whisper_list$',
		views.WhisperListView.as_view(),
		name='whisper-list'),
	url(r'^game/(?P<slug>[-\w]+)/journal$',
		views.EditJournalView.as_view(),
		name='edit-journal'),
	url(r'^game/(?P<slug>[-\w]+)/team_messages$',
		views.TeamMessageListView.as_view(),
		name='team_messages'),
	url(r'^game/(?P<slug>[-\w]+)/report$',
		views.ErrorReportCreateView.as_view(),
		name='new-report'),
	url(r'^game/(?P<slug>[-\w]+)',
		views.GameRouter.as_view(),
		name='show-game'),
)

